# store config in _data for livereload

## site info
author: "Minh-Phuc Bui"
title: "Site title"
title_sep: " - "
description: "A template repository to create simple blog using Jekyll."
logo: "/assets/images/avatar.png"
language: "en"

## global assets will be loaded in head
css:
  - "/assets/css/variables.css"
  - "/assets/css/common.css"
js:
  - "/assets/js/jquery-3.6.0.min.js"
  - "/assets/js/main.js"

## menu
menu:
  - name: "About"
    url: "/about"
  - name: "Contact"
    url: "/contact"

## tags
tag_prepend: "#"
tag_related_title: "Tags"
tag_archive_title: "All tags"

## date
date_pretty_format: "%B %d, %Y"
date_today: "Today"
date_singular_day_ago: "1 day ago"
date_plural_days_ago: "[n] days ago"
date_singular_month_ago: "1 month ago"
date_plural_months_ago: "[n] months ago"
date_singular_year_ago: "1 year ago"
date_plural_years_ago: "[n] years ago"